In [77]:
import pandas as pd
from census import Census 
from config import Api_Key
from config2 import Api_Key2
import json
import requests
import zillow
import pprint
from census import Census 
import PyMongo

ModuleNotFoundError: No module named 'PyMongo'

In [53]:
hist=pd.read_csv('RDC_InventoryCoreMetrics_Zip_Hist.csv')
YearMonth=[]
for item in range(len(hist['Month'])):
    YearMonth.append(hist['Month'][item][:4]+hist['Month'][item][5:7])
hist['Year/Month']=YearMonth
hist.head()

,Month,ZipCode,ZipName,Footnote,Median Listing Price,Median Listing Price M/M,Median Listing Price Y/Y,Active Listing Count,Active Listing Count M/M,Active Listing Count Y/Y,...,Avg Listing Price,Avg Listing Price M/M,Avg Listing Price Y/Y,Total Listing Count,Total Listing Count M/M,Total Listing Count Y/Y,Pending Ratio,Pending Ratio M/M,Pending Ratio Y/Y,Year/Month
0,2019-01-01 00:00:00,1001.0,"Agawam, MA",NaN,201225.0,-0.0340,-0.0574,55.5,-0.1328,0.1809,...,237728.0,-0.0400,-0.0256,56.5,-0.1308,0.1771,0.0180,0.0024,-0.0033,201901
1,2019-01-01 00:00:00,1002.0,"Amherst, MA",NaN,454050.0,0.0682,0.2975,50.0,-0.1803,-0.2857,...,499614.0,0.0395,0.0963,50.0,-0.1803,-0.2857,0.0000,0.0000,0.0000,201901
2,2019-01-01 00:00:00,1005.0,"Barre, MA",NaN,243225.0,0.0132,-0.0243,25.5,-0.1774,0.3421,...,332485.0,0.0236,0.4285,25.5,-0.1774,0.3421,0.0000,0.0000,0.0000,201901
3,2019-01-01 00:00:00,1007.0,"Belchertown, MA",NaN,333775.0,-0.0324,-0.0990,45.0,-0.0426,-0.2174,...,332184.0,-0.0262,-0.0712,45.0,-0.0426,-0.2174,0.0000,0.0000,0.0000,201901
4,2019-01-01 00:00:00,1008.0,"Blandford, MA",NaN,223725.0,-0.0676,0.1834,9.0,-0.2500,0.0000,...,230469.0,-0.0227,0.3313,11.0,-0.2143,0.0000,0.2222,0.0556,0.0000,201901

In [57]:
data=hist[hist['Year/Month']>='201301']
data=data[data['Year/Month']<='201812']
data['Year/Month'].unique()

array(['201812', '201811', '201810', '201809', '201808', '201807',
       '201806', '201805', '201804', '201803', '201802', '201801',
       '201712', '201711', '201710', '201709', '201708', '201707',
       '201706', '201705', '201704', '201703', '201702', '201701',
       '201612', '201611', '201610', '201609', '201608', '201607',
       '201606', '201605', '201604', '201603', '201602', '201601',
       '201512', '201511', '201510', '201509', '201508', '201507',
       '201506', '201505', '201504', '201503', '201502', '201501',
       '201412', '201411', '201410', '201409', '201408', '201407',
       '201406', '201405', '201404', '201403', '201402', '201401',
       '201312', '201311', '201310', '201309', '201308', '201307',
       '201306', '201305', '201304', '201303', '201302', '201301'],
      dtype=object)

In [50]:
from bs4 import BeautifulSoup
import requests
import pymongo
years=['2013', '2014', '2015', '2016', '2017', '2018']
months=['1','2','3','4','5','6','7','8','9','10','11','12']
Rates30y=[]
Rates15y=[]
YearMonth=[]
for year in years:
    for month in months:
        url = 'http://www.mortgagenewsdaily.com/mortgage_rates/charts.asp?Y='+year+'&M='+month
        response = requests.get(url)
        soup = BeautifulSoup(response.text, 'lxml')
        Rates = soup.find_all('td', class_='RateListItem rate')
        Rates30y.append(Rates[0].text)
        Rates15y.append(Rates[2].text)
        if month=='10' or month=='11' or month=='12':
            YearMonth.append(year+month)
        else:
            YearMonth.append(year+'0'+month)

In [51]:
NationaRates=pd.DataFrame({'Year/Month':YearMonth,
                          'Rates30y':Rates30y,
                          'Rates15y':Rates15y})

In [52]:
NationaRates

   Year/Month Rates30y Rates15y
0      201301    2.78%    3.53%
1      201302    2.84%    3.62%
2      201303    2.96%    3.74%
3      201304    3.03%    3.77%
4      201305    2.80%    3.58%
5      201306    3.04%    3.76%
6      201307    3.44%    4.27%
7      201308    3.62%    4.49%
8      201309    3.77%    4.63%
9      201310    3.71%    4.58%
10     201311    3.61%    4.48%
11     201312    3.67%    4.54%
12     201401    3.80%    4.67%
13     201402    3.66%    4.45%
14     201403    3.67%    4.51%
15     201404    3.66%    4.53%
16     201405    3.56%    4.37%
17     201406    3.48%    4.34%
18     201407    3.45%    4.34%
19     201408    3.47%    4.33%
20     201409    3.50%    4.31%
21     201410    3.53%    4.32%
22     201411    3.44%    4.24%
23     201412    3.42%    4.19%
24     201501    3.43%    4.06%
25     201502    3.33%    3.91%
26     201503    3.38%    3.95%
27     201504    3.32%    3.93%
28     201505    3.26%    3.90%
29     201506    3.36%    4.04%
..        ...      ...      ...
42     201607    3.08%    3.80%
43     201608    3.05%    3.74%
44     201609    3.03%    3.74%
45     201610    3.03%    3.73%
46     201611    3.06%    3.76%
47     201612    3.27%    3.80%
48     201701    3.59%    4.37%
49     201702    3.65%    4.41%
50     201703    3.59%    4.24%
51     201704    3.66%    4.04%
52     201705    3.51%    3.97%
53     201706    3.47%    4.15%
54     201707    3.45%    4.14%
55     201708    3.48%    4.19%
56     201709    3.39%    4.14%
57     201710    3.43%    4.11%
58     201711    3.47%    4.17%
59     201712    3.56%    4.17%
60     201801    3.65%    4.19%
61     201802    3.77%    4.36%
62     201803    3.89%    4.54%
63     201804    4.06%    4.64%
64     201805    4.09%    4.71%
65     201806    4.19%    4.76%
66     201807    4.17%    4.77%
67     201808    4.15%    4.78%
68     201809    4.20%    4.77%
69     201810    4.29%    4.87%
70     201811    4.30%    4.99%
71     201812    4.34%    4.98%

[72 rows x 3 columns]

In [73]:
FinalData=pd.merge(data, NationaRates, how='left', on='Year/Month')
FinalData.head()

,Month,ZipCode,ZipName,Footnote,Median Listing Price,Median Listing Price M/M,Median Listing Price Y/Y,Active Listing Count,Active Listing Count M/M,Active Listing Count Y/Y,...,Avg Listing Price Y/Y,Total Listing Count,Total Listing Count M/M,Total Listing Count Y/Y,Pending Ratio,Pending Ratio M/M,Pending Ratio Y/Y,Year/Month,Rates30y,Rates15y
0,2018-12-01 00:00:00,1001.0,"Agawam, MA",NaN,208300.0,0.0158,-0.0309,64.0,-0.1233,0.2308,...,0.0154,65.0,-0.1216,0.2264,0.0156,0.0019,-0.0036,201812,4.34%,4.98%
1,2018-12-01 00:00:00,1002.0,"Amherst, MA",NaN,425050.0,-0.0234,0.2503,61.0,-0.2278,-0.1974,...,0.0655,61.0,-0.2278,-0.1974,0.0000,0.0000,0.0000,201812,4.34%,4.98%
2,2018-12-01 00:00:00,1005.0,"Barre, MA",*,240050.0,-0.0062,NaN,31.0,-0.1143,NaN,...,0.4040,31.0,-0.1143,0.4762,0.0000,0.0000,0.0000,201812,4.34%,4.98%
3,2018-12-01 00:00:00,1007.0,"Belchertown, MA",NaN,344950.0,0.0614,0.0012,47.0,-0.1376,-0.2985,...,-0.0034,47.0,-0.1376,-0.2985,0.0000,0.0000,0.0000,201812,4.34%,4.98%
4,2018-12-01 00:00:00,1008.0,"Blandford, MA",*,239950.0,-0.0266,NaN,12.0,0.0000,NaN,...,-0.0587,14.0,0.0000,0.1667,0.1667,0.0000,-0.0333,201812,4.34%,4.98%

In [83]:
# Initialize PyMongo to work with MongoDBs
conn = 'mongodb://localhost:27017'
client = pymongo.MongoClient(conn)

# Define database and collection
db_ETL = client.ETL_db
finaldata_collection = db_ETL.finaldata

In [84]:
finaldata_collection.insert_many(FinalData.to_dict('records'))